services:
    app.cache:
        class: AppBundle\Cache\Memcached
        arguments: [ "@memcache.default" ]
    cart:
        class: Appbundle\Shop\Cart
        arguments: [ "@app.cache", "@session" ]