<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    /**
     * Get product by alias
     *
     * @param $alias
     *
     * @return null|object
     */
    public function getByAlias($alias) {
        $product = $this->findOneBy(['alias' => $alias]);

        return $product;
    }

    /**
     * Get all products with selected params
     *
     * @param array $params
     *
     * @return array  Product list
     */
    public function getAll($params = [])
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('p');
        $qb->from('AppBundle:Product', 'p');
        $qb->orderBy('p.title');

        if (isset($params['category'])) {
            $qb->where('p.category = :category');
            $qb->setParameter('category', $params['category']);
        }

        $query = $qb->getQuery();
        $products = $query->getResult();

        return $products;
    }
}
