<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getAll($params = [])
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('p');
        $qb->from('AppBundle:Product', 'p');
        $qb->orderBy('p.title');

        if (isset($params['category'])) {
            $qb->where('p.category_id = ?', $params['category']);
        }

        $query = $qb->getQuery();
        $products = $query->getResult();

        return $products;
    }
}
